### ISSUE TITLE
Nice idea

### ISSUE THREAD

**Issue by JuicyLung91** [Tschucki/shopware-servant#1]
Not a real issue but i like your idea. Its like the laravel artisan for shopware. 

I once started something similar https://github.com/pureware/pureware-cli

If you need some inspiration.

I use Symfony and not laravel just to stay inside the framework that shopware is using and use twig templates for the boilerplates. 

How do you want to handle different shopware versions?

**Comment by Tschucki** [comment]
Thank you.

I can switch easy between the separate commands based on the Shopware project version.
